# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: dev-info

  profiles:
    active: dev

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 로깅 설정(공통)
logging:
  level:
    root: INFO
    com.study.profile_stack_api: DEBUG
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG

jwt:
  secret: "YourBase64EncodedSecretKeyHereMustBeAtLeast256BitsLong!!"
  access-token-expiration: 1800    # 30분 (초)
  refresh-token-expiration: 604800 # 7일 (초)

# 문서환
springdoc:
  # Swagger UI 경로 설정
  swagger-ui:
    path: /swagger-ui.html
    # API 목록을 그룹별로 표시
    groups-order: DESC
    # 태그를 알파벳 순으로 정렬
    tags-sorter: alpha
    # 오퍼레이션을 HTTP 메서드 순으로 정렬
    operations-sorter: method
    # Try it out 기능 기본 활성화
    disable-swagger-default-url: true
    # 요청 소요 시간 표시
    display-request-duration: true

  # OpenAPI 문서 경로
  api-docs:
    path: /v1/api-docs
    enabled: true

  # 패키지 경로 스캔 설정
  packages-to-scan: com.study.profile_stack_api